(define (problem capture-legendary-dogs)
    (:domain pokemon-world)

    (:objects 
        ash - player
        raikou entei suicune - legendarypokemon
        item1 item2 item3 - chest
        masterball1 masterball2 masterball3 - masterball
        grassfield0 grassfield2 grassfield3 grassfield4 grassfield5 grassfield6 grassfield7 grassfield8 grassfield9 grassfield10 grassfield11 grassfield12 grassfield13 grassfield14 grassfield15 grassfield16 grassfield17 grassfield18 grassfield19 grassfield20 grassfield21 grassfield22 grassfield23 grassfield24 grassfield24 - location
    )

    (:init
        (border grassfield0 grassfield1)
        (border grassfield1 grassfield0)
        (border grassfield0 grassfield5)
        (border grassfield5 grassfield0)
        (border grassfield1 grassfield2)
        (border grassfield2 grassfield1)
        (border grassfield1 grassfield6)
        (border grassfield6 grassfield1)
        (border grassfield2 grassfield3)
        (border grassfield3 grassfield2)
        (border grassfield2 grassfield7)
        (border grassfield7 grassfield2)
        (border grassfield3 grassfield4)
        (border grassfield4 grassfield3)
        (border grassfield3 grassfield8)
        (border grassfield8 grassfield3)
        (border grassfield4 grassfield9)
        (border grassfield9 grassfield4)
        (border grassfield5 grassfield6)
        (border grassfield6 grassfield5)
        (border grassfield5 grassfield10)
        (border grassfield10 grassfield5)
        (border grassfield6 grassfield7)
        (border grassfield7 grassfield6)
        (border grassfield6 grassfield11)
        (border grassfield11 grassfield6)
        (border grassfield7 grassfield8)
        (border grassfield8 grassfield7)
        (border grassfield7 grassfield12)
        (border grassfield12 grassfield7)
        (border grassfield8 grassfield9)
        (border grassfield9 grassfield8)
        (border grassfield8 grassfield13)
        (border grassfield13 grassfield8)
        (border grassfield9 grassfield14)
        (border grassfield14 grassfield9)
        (border grassfield10 grassfield11)
        (border grassfield11 grassfield10)
        (border grassfield10 grassfield15)
        (border grassfield15 grassfield10)
        (border grassfield11 grassfield12)
        (border grassfield12 grassfield11)
        (border grassfield11 grassfield16)
        (border grassfield16 grassfield11)
        (border grassfield12 grassfield13)
        (border grassfield13 grassfield12)
        (border grassfield12 grassfield17)
        (border grassfield17 grassfield12)
        (border grassfield13 grassfield14)
        (border grassfield14 grassfield13)
        (border grassfield13 grassfield18)
        (border grassfield18 grassfield13)
        (border grassfield14 grassfield19)
        (border grassfield19 grassfield14)
        (border grassfield15 grassfield16)
        (border grassfield16 grassfield15)
        (border grassfield15 grassfield20)
        (border grassfield20 grassfield15)
        (border grassfield16 grassfield17)
        (border grassfield17 grassfield16)
        (border grassfield16 grassfield21)
        (border grassfield21 grassfield16)
        (border grassfield17 grassfield18)
        (border grassfield18 grassfield17)
        (border grassfield17 grassfield22)
        (border grassfield22 grassfield17)
        (border grassfield18 grassfield19)
        (border grassfield19 grassfield18)
        (border grassfield18 grassfield23)
        (border grassfield23 grassfield18)
        (border grassfield19 grassfield24)
        (border grassfield24 grassfield19)
        (border grassfield20 grassfield21)
        (border grassfield21 grassfield20)
        (border grassfield21 grassfield22)
        (border grassfield22 grassfield21)
        (border grassfield22 grassfield23)
        (border grassfield23 grassfield22)
        (border grassfield23 grassfield24)
        (border grassfield24 grassfield23)

        (wall grassfield2)
        (wall grassfield3)
        (wall grassfield6)
        (wall grassfield7)
        (wall grassfield16)
        (wall grassfield18)
        (wall grassfield21)

        (at ash grassfield22)
        (at raikou grassfield4)
        (at entei grassfield23)
        (at suicune grassfield20)
        (at item1 grassfield1)
        (at item2 grassfield9)
        (at item3 grassfield24)

        (in masterball1 item1)
        (in masterball2 item2)
        (in masterball1 item1)

    )

    (:goal (and (has-three-legendary-pokemon ash)))

)